---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec: {}
---
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: thanos-storage-claim
  namespace: open-cluster-management
spec:
  name: thanos-storage
---
kind: MultiClusterObservability
apiVersion: observability.open-cluster-management.io/v1beta2
metadata:
  name: observability
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
