---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
    name: spokes
    namespace: policies
spec:
    clusterSet: 
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
    name: hub
    namespace: policies
spec:
    clusterSet: hub

