---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devspaces
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: spoke-cluster-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'devspaces-{{name}}'
    spec:
      destination:
        namespace: openshift-operators
        server: ''{{server}}''
      project: default
      source:
        path: 3-operators/devspaces/overlays/latest
        repoURL: >-
          git@github.com:rosa-as-a-service/hub-rosa-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
