---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Red Hat Operators"
    openshift.io/display-name: "Red Hat Operators"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-operators-redhat