---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: elasticsearch
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: <change-me>
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
