apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ClusterLogForwarder
      name: instance
      namespace: openshift-logging
    patch: |-
      - op: replace
        path: /spec/outputs/0/cloudwatch/groupPrefix
        value: 'rosa-spoke'