apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
spec:
  clusterName: |
    {{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}
  auditLogs:
    collection: Auto
  centralEndpoint: |
    {{hub fromSecret "policies" "sensor-tls" "acs-host" | base64dec hub}}
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  scanner:
    scannerComponent: Disabled
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
---
apiVersion: v1
data:
  admission-control-cert.pem: '{{hub fromSecret "policies" "admission-control-tls" "admission-control-cert.pem" hub}}'
  admission-control-key.pem: '{{hub fromSecret "policies" "admission-control-tls" "admission-control-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "policies" "admission-control-tls" "ca.pem" hub}}'
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data:
  collector-cert.pem: '{{hub fromSecret "policies" "collector-tls" "collector-cert.pem" hub}}'
  collector-key.pem: '{{hub fromSecret "policies" "collector-tls" "collector-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "policies" "collector-tls" "ca.pem" hub}}'
kind: Secret
metadata:
  name: collector-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data:
  sensor-cert.pem: '{{hub fromSecret "policies" "sensor-tls" "sensor-cert.pem" hub}}'
  sensor-key.pem: '{{hub fromSecret "policies" "sensor-tls" "sensor-key.pem" hub}}'
  ca.pem: '{{hub fromSecret "policies" "sensor-tls" "ca.pem" hub}}'
  acs-host: '{{hub fromSecret "policies" "sensor-tls" "acs-host" hub}}'
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
type: Opaque
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs
spec:
  applicationMenu:
    section: Red Hat applications
    imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg'
  href: https://{{ (lookup "route.openshift.io/v1" "Route" "acs-instance" "central").spec.host }}
  location: ApplicationMenu
  text: 'Red Hat Advanced Cluster Security for Kubernetes'
