apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-ansible-automation-platform
resources:
  - namespace.yml
  - operatorgroup.yml
  - subscription.yml
  - controller.yml
  - controller_route.yml
  - hub.yml
  - hub_route.yml
  - eda.yml
  - eda_route.yml