apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - target:
      kind: Subscription
      name: odf-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-4.12'
