---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    type: vector
  logStore:
    elasticsearch:
      resources:
        requests:
          memory: 2Gi
      storage:
        size: 200G
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
    retentionPolicy:
      application:
        maxAge: 7d
    type: elasticsearch
  visualization:
    kibana:
      replicas: 1
    type: kibana
  managementState: Managed
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  outputs:
    - cloudwatch:
        groupBy: namespaceName
        groupPrefix: rosa-hub # template this for spokes
        region: ap-southeast-2
      name: cloudwatch
      secret:
        name: aws-credentials
      type: cloudwatch
  pipelines:
    - inputRefs:
        - application
        - audit
        - infrastructure
      name: forward-to-cloudwatch
      outputRefs:
        - cloudwatch