---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceAccount:
    name: cluster-logging
  outputs:
    - name: default-lokistack
      type: lokiStack
      lokiStack:
        target:
          name: logging-loki
          namespace: openshift-logging
        authentication:
          token:
            from: serviceAccount
    - name: cloudwatch
      type: cloudwatch
      cloudwatch:
        groupPrefix: rosa-hub
        region: ap-southeast-2
      tls:
        insecureSkipVerify: false
      authentication:
        awsAccessKey:
          keyId:
            secretName: aws-credentials
            key: aws_access_key_id
          keySecret:
            secretName: aws-credentials
            key: aws_secret_access_key
  pipelines:
    - name: all-to-lokistack
      inputRefs:
        - application
        - audit
        - infrastructure
      outputRefs:
        - default-lokistack
    - name: all-to-cloudwatch
      inputRefs:
        - application
        - audit
        - infrastructure
      outputRefs:
        - cloudwatch
