apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acs-instance
bases:
  - ../../base

patches:
  - target: 
      kind: Central
      name: central
    patch: |-
      - op: replace
        path: /spec/central
        value:
          exposure:
            loadBalancer:
              enabled: false
              port: 443
            nodePort:
              enabled: false
            route:
              enabled: true
          persistence:
            persistentVolumeClaim:
              claimName: stackrox-db
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: 600m
              memory: 2Gi
          db:
            resources:
              limits:
                cpu: '2'
                memory: 4Gi
              requests:
                cpu: '2'
                memory: 4Gi
      - op: replace
        path: /spec/scanner
        value:
          analyzer:
            scaling:
              autoScaling: Enabled
              maxReplicas: 5
              minReplicas: 2
              replicas: 2
          scannerComponent: Enabled
          db:
            resources:
              limits:
                cpu: '1'
                memory: 2Gi
              requests:
                cpu: '1'
                memory: 1000Mi