apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acs-instance
bases:
  - ../../base

patches:
  - target: 
      group: platform.stackrox.io/v1alpha1
      kind: Central
      name: central
    patch: |-
      - op: add
        path: /spec/central/resources
        value:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 600m
            memory: 2Gi
      - op: add
        path: /spec/central/db/resources
        value:
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
      - op: add
        path: /spec/scanner/resources
        value:
          resources:
            limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1000Mi