---
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: classification-banner
spec:
  backgroundColor: '#4E92F6'
  color: '#FFFFFF'
  location: BannerTop
  text: "<change-me>"