---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
   name: cluster
spec:
   customization:
      customLogoFile:
         name: console-custom-logo
         key: console-custom-logo.png