---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-logo
  namespace: openshift-config
binaryData:
  custom-logo.png: <change-me>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-logo
  namespace: openshift-console
binaryData:
  custom-logo.png: <change-me>