apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-3.9'
    target:
      kind: Subscription
      name: quay-operator