---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ack-s3
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: ack-system
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 3-operators/ack-s3/overlays/alpha
    repoURL: >-
      git@github.com:rosa-as-a-service/hub-rosa-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
