---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 3-operators/odf/overlays/stable-4.12
    repoURL: >-
      git@github.com:rosa-as-a-service/hub-rosa-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
